apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudshop-deployment
spec:
  selector:
    matchLabels:
      app: cloudshop
  replicas: 3
  template:
    metadata:
      labels:
        app: cloudshop
    spec:
     containers:
     - name: cloudshop
       image: guzmanjuan/cloudshop
       imagePullPolicy: Always
       ports:
       - containerPort: 80